
package com.apasny.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Command", targetNamespace = "http://service.commandj11.example.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Command {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/saveUserRequest", output = "http://service.commandj11.example.com/Command/saveUserResponse")
    public String saveUser(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/addUserToGroupRequest", output = "http://service.commandj11.example.com/Command/addUserToGroupResponse")
    public String addUserToGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.apasny.soap.SetOfUser
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getAllUsersInGroupRequest", output = "http://service.commandj11.example.com/Command/getAllUsersInGroupResponse")
    public SetOfUser getAllUsersInGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getAllUsersRequest", output = "http://service.commandj11.example.com/Command/getAllUsersResponse")
    public String getAllUsers();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/getUserRequest", output = "http://service.commandj11.example.com/Command/getUserResponse")
    public String getUser();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/deleteUserFromGroupRequest", output = "http://service.commandj11.example.com/Command/deleteUserFromGroupResponse")
    public String deleteUserFromGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.commandj11.example.com/Command/createGroupRequest", output = "http://service.commandj11.example.com/Command/createGroupResponse")
    public String createGroup(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
